export const style = {
    flexCenter: 'flex justify-center items-center',
    flexStart: 'flex justify-center items-start',
    flexEnd: 'flex justify-end items-start',
    flexStart2: 'flex justify-start items-center',
    flexEvenly: 'justify-evenly flex items-center',
    flexBtw: 'justify-between flex items-center',
    flexBtw2: 'justify-between flex items-end',
    flexMobile1: 'md:flex-row flex-col',
    flexMobile2: 'flex md:flex-row flex-col',
    flexY: 'flex flex-col',
    widthMobile: 'md:w-[50%] w-[100%]',
    position: 'md:absolute relative',
    headings1: 'md:text-5xl text-3xl archivo font-black text-center',
    headings2: 'md:text-5xl text-3xl archivo font-black text-left',
    headings3: 'md:text-3xl text-2xl archivo font-black ',
    subHeading: 'text-base text-center',
    subHeading2: 'text-base text-left',
    pageX:  'px-[4%]',
    pagePad: 'px-[4%] py-[5%]'
}